[package]
name = "dang"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "~0.20.10"
tree-sitter-dang = { path = "tree-sitter-dang" }
rustyline = "14.0.0"
dirs = "5.0.1"
pest = "2.7.10"
pest_derive = { version = "2.7.10", features = ["grammar-extras"] }
clap = { version = "4.5.7", features = ["derive"] }
unescape = "0.1.0"
include_dir = "0.7.4"
regex = "1.10.5"
assert_matches = "1.5.0"
lazy_static = "1.5.0"
ustr = "1.0.0"
pretty = { version = "0.12.3", features = ["termcolor"] }
escape8259 = "0.5.3"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26"

[features]
stats = []
flamegraph = []

[[tests]]
