WHITESPACE = _{ " " | "\t" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }

// Places where optional newlines can go
nl = _{ NEWLINE* }

source_file = _{ SOI ~ nl ~ stmt* ~ nl ~ EOI }

body = { nl ~ "{" ~ nl ~ stmt* ~ nl ~ "}" ~ nl }

keywords = {
  "false" |
  "fn" |
  "for" |
  "let" |
  "true" |
  "var" |
  "if" |
  "else" |
  "nil"
}

identifier = @{ !keywords ~ !ASCII_DIGIT ~ (ASCII_ALPHANUMERIC | "_")+ }

stmt = _{
  (let_stmt | var_stmt | assignment | if_stmt | for_stmt | expr) ~ stmt_end
}

stmt_end = _{ NEWLINE* ~ ";"? }

let_stmt = { "let" ~ identifier ~ "=" ~ nl ~ expr }
var_stmt = { "var" ~ identifier ~ "=" ~ nl ~ expr }
assignment = { identifier ~ "=" ~ nl ~ expr }
if_stmt = {
  "if" ~
  #cond = expr ~
  #if_body = body ~
  ( "else" ~ ( #else_if = if_stmt | #else_body = body ) )?
}
for_stmt = { "for" ~ identifier ~ "in" ~ expr ~ body }

expr = { prefix? ~ primary ~ (infix ~ nl ~ prefix? ~ nl ~ primary )* }
  infix    =  _{ mul | div | add | sub | gte | gt | lte | lt | eq | neq | logical_and | logical_or }
    mul    =   { "*" } // Multiplication
    div    =   { "/" } // Division
    add    =   { "+" } // Addition
    sub    =   { "-" } // Subtraction
    gte    =   { ">=" }
    gt     =   { ">" }
    lte    =   { "<=" }
    lt     =   { "<" }
    eq     =   { "==" }
    neq    =   { "!=" }
    logical_and = { "&&" }
    logical_or  = { "||" }
  prefix   =  _{ neg | logical_neg }
    neg    =   { "-" } // Integer regation
    logical_neg = { "!" } // logical negation
  primary  =  _{ term | "(" ~ nl ~ expr ~ nl ~ ")" }

term = {
  ( function_literal |
    function_call |
    identifier |
    list_literal |
    nil_literal |
    bool_literal |
    string_literal |
    number_literal ) ~ subscript*
}

subscript = { "[" ~ nl ~ expr ~ nl ~ "]" }

function_literal = { "fn" ~ nl ~ arg_names ~ nl ~ body }

arg_names = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ identifier ~ nl ~ ("," ~ nl ~ identifier ~ nl )* ~ ")"
}

function_call = { identifier ~ args }

args = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ expr ~ nl ~ ("," ~ nl ~ expr ~ nl )* ~ ")"
}

list_literal = {
  "[" ~ nl ~ "]" |
  "[" ~ nl ~ expr ~ nl ~ ("," ~ nl ~ expr ~ nl)* ~ "]"
}

string_literal = ${ "\"" ~ string_contents ~ "\"" }
string_contents = @{ char* }
char = _{
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

number_literal = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}

nil_literal = { "nil" }
bool_literal = { "true" | "false" }
