WHITESPACE = _{ " " | "\t" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }

// Places where optional newlines can go
nl = _{ NEWLINE* }

source_file = _{ SOI ~ nl ~ module? ~ nl ~ import* ~ nl ~ struct_def? ~ nl ~ stmt* ~ nl ~ EOI }

body = { nl ~ "{" ~ nl ~ stmt* ~ nl ~ "}" ~ nl }

keywords = {
  "false" |
  "fn" |
  "for" |
  "let" |
  "true" |
  "var" |
  "if" |
  "else" |
  "nil" |
  "import" |
  "module" |
  "__builtin" |
  "struct" |
  "match"
}

// module Std/Enum
module = { "module" ~ full_module_name ~ stmt_end }
full_module_name = @{ !keywords ~ !ASCII_DIGIT ~ (ASCII_ALPHANUMERIC | "_" | "/")+ }

// import Std/Enum
// import Std/Enum.run
// import Std/Enum.*
import = { "import" ~ import_ref ~ stmt_end }
import_ref = ${ full_module_name ~ (import_all | ("." ~ identifier))? }
import_all = { ".*" }

// struct {
//   a: 1,
//   b,
//   c: 3
// }

struct_def = {
  "struct" ~ nl ~ "{" ~ nl ~ "}" |
  "struct" ~ nl ~ "{" ~ struct_def_field ~ ("," ~ struct_def_field)* ~ ","? ~ nl ~ "}"
}
struct_def_field = {
  nl ~ identifier ~ nl ~ ":" ~ nl ~ expr ~ nl |
  nl ~ identifier ~ nl
}

identifier = @{ !keywords ~ !ASCII_DIGIT ~ (ASCII_ALPHANUMERIC | "_")+ ~ "?"? }

stmt = _{
  (builtin_stmt | let_stmt | var_stmt | field_assignment | assignment | if_stmt | for_stmt | expr) ~ stmt_end
}

stmt_end = _{ NEWLINE* ~ ";"? }

// To define built-in functions in code (so they have AST nodes)
//
//  __builtin print
//  __builtin println
//  __builtin raise
//
//  etc..
builtin_stmt = { "__builtin" ~ identifier }

let_stmt = { "let" ~ pattern ~ "=" ~ nl ~ expr }
var_stmt = { "var" ~ pattern ~ "=" ~ nl ~ expr }
assignment = { pattern ~ "=" ~ nl ~ expr }
field_assignment = { field_assignment_path ~ "=" ~ nl ~ expr }
if_stmt = {
  "if" ~
  #cond = expr ~
  #if_body = body ~
  ( "else" ~ ( #else_if = if_stmt | #else_body = body ) )?
}
for_stmt = { "for" ~ pattern ~ "in" ~ expr ~ body }

field_assignment_path = {
  variable_ref ~ (subscript | field_access)+
}

pattern = {
  pattern_constant |
  pattern_identifier |
  pattern_tuple |
  pattern_list
}
pattern_constant = {
  nil_literal |
  bool_literal |
  string_literal |
  number_literal |
  symbol_literal
}
pattern_identifier = { identifier }

expr = { prefix? ~ primary ~ (infix ~ nl ~ prefix? ~ nl ~ primary )* }
  infix    =  _{ pipe | mul | div | add | sub | gte | gt | lte | lt | eq | neq | logical_and | logical_or }
    pipe   =   { NEWLINE* ~ "|>" }  // Elixir style pipe operator
    mul    =   { "*" } // Multiplication
    div    =   { "/" } // Division
    add    =   { "+" } // Addition
    sub    =   { "-" } // Subtraction
    gte    =   { ">=" }
    gt     =   { ">" }
    lte    =   { "<=" }
    lt     =   { "<" }
    eq     =   { "==" }
    neq    =   { "!=" }
    logical_and = { "&&" }
    logical_or  = { "||" }
  prefix   =  _{ neg | logical_neg }
    neg    =   { "-" } // Integer regation
    logical_neg = { "!" } // logical negation
  primary  =  _{ match_expr | term | "(" ~ nl ~ expr ~ nl ~ ")" }

match_expr = { "match" ~ nl ~ expr ~ nl ~ "{" ~ nl ~ match_case+ ~ nl ~ "}" }
match_case = { pattern ~ ("if" ~ expr)? ~ "->" ~ nl ~ (expr | body) ~ ","? ~ nl }

term = {
  ( function_literal |
    function_call |
    struct_literal |
    variable_ref |
    tuple_literal |
    list_literal |
    dict_literal |
    nil_literal |
    bool_literal |
    string_literal |
    number_literal |
    symbol_literal ) ~ (subscript | field_access | call)*
}

variable_ref = { identifier }

subscript = { "[" ~ nl ~ expr ~ nl ~ "]" }
field_access = { "." ~ identifier }

function_literal = { "fn" ~ nl ~ arg_names ~ nl ~ body }

arg_names = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ identifier ~ nl ~ ("," ~ nl ~ identifier ~ nl )* ~ ")"
}

function_call = { variable_ref ~ args }

call = { args }

args = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ expr ~ nl ~ ("," ~ nl ~ expr ~ nl )* ~ ")"
}

tuple_literal = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ expr ~ nl ~ "," ~ ")" | // single element requires trailing , to disambiguate
  "(" ~ nl ~ expr ~ nl ~ ("," ~ nl ~ expr ~ nl)+ ~ ","? ~ nl ~ ")"
}

pattern_tuple = {
  "(" ~ nl ~ ")" |
  "(" ~ nl ~ pattern ~ nl ~ "," ~ ")" | // single element requires trailing , to disambiguate
  "(" ~ nl ~ pattern ~ nl ~ ("," ~ nl ~ pattern ~ nl)+ ~ ","? ~ nl ~ ")"
}

list_literal = {
  "[" ~ nl ~ "]" |
  "[" ~ nl ~ expr ~ nl ~ ("," ~ nl ~ expr ~ nl)* ~ ","? ~ nl ~ "]"
}

pattern_list = {
  "[" ~ nl ~ "]" |
  "[" ~ nl ~ pattern ~ nl ~ ("," ~ nl ~ pattern ~ nl)* ~ ","? ~ nl ~ "]"
}

dict_literal = {
  "{" ~ nl ~ "}" |
  "{" ~ dict_kv ~ ("," ~ dict_kv)* ~ ","? ~ nl ~ "}"
}
dict_kv = {
  nl ~ symbol_dict_key ~ nl ~ ":" ~ nl ~ expr ~ nl |
  nl ~ expr ~ nl ~ "=>" ~ nl ~ expr ~ nl
}
symbol_dict_key = { identifier }

struct_literal = {
  struct_start ~ nl ~ "}" |
  struct_start ~ struct_field ~ ("," ~ struct_field)* ~ ","? ~ nl ~ "}"
}
struct_start = ${ variable_ref ~ "{" }
struct_field = { nl ~ identifier ~ nl ~ ":" ~ nl ~ expr ~ nl }

string_literal = ${ "\"" ~ string_contents ~ "\"" }
string_contents = @{ char* }
char = _{
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

number_literal = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}

nil_literal = { "nil" }
bool_literal = { "true" | "false" }

symbol_literal = ${ ":" ~ (identifier | string_literal) }
