WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }

source_file = _{ SOI ~ stmt* ~ EOI }

identifier = @{ !ASCII_DIGIT ~ (ASCII_ALPHANUMERIC | "_")+ }

stmt = _{ let_stmt | var_stmt | assignment | expr }

let_stmt = { "let" ~ identifier ~ "=" ~ expr }
var_stmt = { "var" ~ identifier ~ "=" ~ expr }
assignment = { identifier ~ "=" ~ expr }

expr = { prefix? ~ primary ~ (infix ~ prefix? ~ primary )* }
  infix    =  _{ add | sub | mul | div }
    add    =   { "+" } // Addition
    sub    =   { "-" } // Subtraction
    mul    =   { "*" } // Multiplication
    div    =   { "/" } // Division
  prefix   =  _{ neg }
    neg    =   { "-" } // Negation
  primary  =  _{ term | "(" ~ expr ~ ")" }

term = _{ function_call | identifier | string_literal | number_literal }

function_call = { identifier ~ args }

args = {
  "(" ~ ")" |
  "(" ~ expr ~ ("," ~ expr)* ~ ")"
}

string_literal = ${ "\"" ~ string_contents ~ "\"" }
string_contents = @{ char* }
char = _{
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

number_literal = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}
